export const SUBMIT = "SUBMIT";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const CHANGE_BUTTON_NAME = "CHANGE_BUTTON_NAME";